[I 11:16:34.600 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 11:16:34.942 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 11:16:34.945 NotebookApp] Serving notebooks from local directory: /root/projects/binanceapp
[I 11:16:34.945 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 11:16:34.945 NotebookApp] http://localhost:8888/
[I 11:16:34.945 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 11:16:34.952 NotebookApp] No web browser found: could not locate runnable browser.
[W 11:16:56.376 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 11:16:56.577 NotebookApp] Kernel started: f370aeca-fd98-495d-a041-7b57604bf690, name: python3
ERROR:asyncio:Exception in callback <TaskStepMethWrapper object at 0x7f2829ae90b8>()
handle: <Handle <TaskStepMethWrapper object at 0x7f2829ae90b8>()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>
[I 11:18:56.604 NotebookApp] Saving file at /binance_first.ipynb
[I 11:20:57.023 NotebookApp] Saving file at /binance_first.ipynb
[I 11:22:57.796 NotebookApp] Saving file at /binance_first.ipynb
[I 11:24:56.786 NotebookApp] Saving file at /binance_first.ipynb
[I 11:26:58.085 NotebookApp] Saving file at /binance_first.ipynb
[I 11:28:57.689 NotebookApp] Saving file at /binance_first.ipynb
[I 11:34:57.980 NotebookApp] Saving file at /binance_first.ipynb
[I 11:36:56.918 NotebookApp] Saving file at /binance_first.ipynb
[I 11:49:00.314 NotebookApp] Saving file at /binance_first.ipynb
[I 11:50:58.713 NotebookApp] Saving file at /binance_first.ipynb
[I 11:52:57.796 NotebookApp] Saving file at /binance_first.ipynb
[I 11:58:57.861 NotebookApp] Saving file at /binance_first.ipynb
[W 12:02:58.315 NotebookApp] WebSocket ping timeout after 119953 ms.
[I 12:03:03.318 NotebookApp] Starting buffering for f370aeca-fd98-495d-a041-7b57604bf690:23d84af07c5b435cb1ff99fbd4c583f2
[I 12:14:29.649 NotebookApp] Kernel restarted: f370aeca-fd98-495d-a041-7b57604bf690
[I 12:14:29.759 NotebookApp] Restoring connection for f370aeca-fd98-495d-a041-7b57604bf690:23d84af07c5b435cb1ff99fbd4c583f2
[W 12:14:34.272 NotebookApp] Nudge: attempt 10 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:14:39.286 NotebookApp] Nudge: attempt 20 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:14:44.300 NotebookApp] Nudge: attempt 30 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:14:49.315 NotebookApp] Nudge: attempt 40 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:14:54.330 NotebookApp] Nudge: attempt 50 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[I 12:14:56.791 NotebookApp] Saving file at /binance_first.ipynb
[W 12:14:59.352 NotebookApp] Nudge: attempt 60 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:04.367 NotebookApp] Nudge: attempt 70 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:09.381 NotebookApp] Nudge: attempt 80 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:14.396 NotebookApp] Nudge: attempt 90 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:19.411 NotebookApp] Nudge: attempt 100 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:24.222 NotebookApp] Notebook binance_first.ipynb is not trusted
[W 12:15:24.911 NotebookApp] Nudge: attempt 110 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:29.651 NotebookApp] Timeout waiting for kernel_info_reply: f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:29.689 NotebookApp] Nudge: attempt 10 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[I 12:15:29.761 NotebookApp] Replaying 3 buffered messages
[E 12:15:29.765 NotebookApp] Uncaught exception GET /api/kernels/f370aeca-fd98-495d-a041-7b57604bf690/channels?session_id=23d84af07c5b435cb1ff99fbd4c583f2 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8800', method='GET', uri='/api/kernels/f370aeca-fd98-495d-a041-7b57604bf690/channels?session_id=23d84af07c5b435cb1ff99fbd4c583f2', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
    tornado.util.TimeoutError: Timeout
[W 12:15:34.701 NotebookApp] Nudge: attempt 20 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:39.714 NotebookApp] Nudge: attempt 30 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:44.730 NotebookApp] Nudge: attempt 40 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:49.744 NotebookApp] Nudge: attempt 50 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[W 12:15:54.759 NotebookApp] Nudge: attempt 60 on kernel f370aeca-fd98-495d-a041-7b57604bf690
[I 12:15:56.398 NotebookApp] Interrupted...
[I 12:15:56.399 NotebookApp] Shutting down 1 kernel
[I 12:15:56.399 NotebookApp] Kernel shutdown: f370aeca-fd98-495d-a041-7b57604bf690
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/decorator.py", line 231, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 567, in initialize
    self.init_sockets()
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 266, in init_sockets
    self.context = context = zmq.Context()
  File "zmq/backend/cython/context.pyx", line 53, in zmq.backend.cython.context.Context.__cinit__
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
[I 12:15:56.703 NotebookApp] Shutting down 0 terminals
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=TimeoutError('Timeout waiting for restart',)>
TimeoutError: Timeout waiting for restart
[I 12:16:01.747 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 12:16:02.123 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 12:16:02.127 NotebookApp] Serving notebooks from local directory: /root/projects/binanceapp
[I 12:16:02.127 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 12:16:02.127 NotebookApp] http://localhost:8888/
[I 12:16:02.127 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 12:16:02.133 NotebookApp] No web browser found: could not locate runnable browser.
[I 12:16:16.444 NotebookApp] 302 GET / (127.0.0.1) 0.980000ms
[W 12:16:19.651 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 12:16:20.164 NotebookApp] Kernel started: 55be3dfa-8973-4c59-8718-a5b9078a9bb3, name: python3
ERROR:asyncio:Exception in callback <TaskStepMethWrapper object at 0x7fbca7297400>()
handle: <Handle <TaskStepMethWrapper object at 0x7fbca7297400>()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>
[I 12:18:20.297 NotebookApp] Saving file at /binance_first.ipynb
[W 12:18:20.298 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 12:20:20.607 NotebookApp] Saving file at /binance_first.ipynb
[W 12:20:20.607 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 12:22:20.595 NotebookApp] Saving file at /binance_first.ipynb
[W 12:22:20.596 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 12:24:20.311 NotebookApp] Saving file at /binance_first.ipynb
[W 12:24:20.312 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 12:27:13.574 NotebookApp] Starting buffering for 55be3dfa-8973-4c59-8718-a5b9078a9bb3:b5e34d690325416b8210b32e759bd997
[I 12:27:14.087 NotebookApp] Kernel restarted: 55be3dfa-8973-4c59-8718-a5b9078a9bb3
[I 12:27:14.184 NotebookApp] Restoring connection for 55be3dfa-8973-4c59-8718-a5b9078a9bb3:b5e34d690325416b8210b32e759bd997
[I 12:27:14.932 NotebookApp] Replaying 6 buffered messages
[I 12:28:20.196 NotebookApp] Saving file at /binance_first.ipynb
[I 12:30:20.521 NotebookApp] Saving file at /binance_first.ipynb
[I 12:33:09.430 NotebookApp] Creating new notebook in 
[I 12:33:10.645 NotebookApp] Kernel started: ed51175a-66ef-4154-8209-1d196c06f6c0, name: python3
[W 12:34:10.748 NotebookApp] Timeout waiting for kernel_info reply from ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:34:15.264 NotebookApp] Nudge: attempt 10 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:34:20.278 NotebookApp] Nudge: attempt 20 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:34:25.291 NotebookApp] Nudge: attempt 30 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:34:30.306 NotebookApp] Nudge: attempt 40 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:34:35.321 NotebookApp] Nudge: attempt 50 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:34:40.334 NotebookApp] Nudge: attempt 60 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:34:45.350 NotebookApp] Nudge: attempt 70 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:34:50.366 NotebookApp] Nudge: attempt 80 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:34:55.382 NotebookApp] Nudge: attempt 90 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:35:00.397 NotebookApp] Nudge: attempt 100 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:35:05.413 NotebookApp] Nudge: attempt 110 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:35:10.429 NotebookApp] Nudge: attempt 120 on kernel ed51175a-66ef-4154-8209-1d196c06f6c0
[I 12:35:10.692 NotebookApp] Saving file at /Untitled.ipynb
[E 12:35:10.753 NotebookApp] Uncaught exception GET /api/kernels/ed51175a-66ef-4154-8209-1d196c06f6c0/channels?session_id=3d38f4c1d21a4f888fe5ed13cf4da96c (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8800', method='GET', uri='/api/kernels/ed51175a-66ef-4154-8209-1d196c06f6c0/channels?session_id=3d38f4c1d21a4f888fe5ed13cf4da96c', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
    tornado.util.TimeoutError: Timeout
[W 12:35:11.856 NotebookApp] Replacing stale connection: ed51175a-66ef-4154-8209-1d196c06f6c0:3d38f4c1d21a4f888fe5ed13cf4da96c
[I 12:35:47.359 NotebookApp] Kernel restarted: ed51175a-66ef-4154-8209-1d196c06f6c0
[W 12:35:47.779 NotebookApp] Replacing stale connection: ed51175a-66ef-4154-8209-1d196c06f6c0:3d38f4c1d21a4f888fe5ed13cf4da96c
[W 12:36:47.361 NotebookApp] Timeout waiting for kernel_info_reply: ed51175a-66ef-4154-8209-1d196c06f6c0
[I 12:37:10.683 NotebookApp] Saving file at /gmail_send_mail.ipynb
[I 12:39:11.815 NotebookApp] Starting buffering for ed51175a-66ef-4154-8209-1d196c06f6c0:3d38f4c1d21a4f888fe5ed13cf4da96c
[W 12:39:14.505 NotebookApp] Replacing stale connection: ed51175a-66ef-4154-8209-1d196c06f6c0:3d38f4c1d21a4f888fe5ed13cf4da96c
[W 12:39:51.805 NotebookApp] Replacing stale connection: ed51175a-66ef-4154-8209-1d196c06f6c0:3d38f4c1d21a4f888fe5ed13cf4da96c
[W 12:43:23.509 NotebookApp] Replacing stale connection: ed51175a-66ef-4154-8209-1d196c06f6c0:3d38f4c1d21a4f888fe5ed13cf4da96c
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=TimeoutError('Timeout waiting for restart',)>
TimeoutError: Timeout waiting for restart
[W 12:44:08.831 NotebookApp] Replacing stale connection: ed51175a-66ef-4154-8209-1d196c06f6c0:3d38f4c1d21a4f888fe5ed13cf4da96c
[W 12:47:56.530 NotebookApp] Replacing stale connection: ed51175a-66ef-4154-8209-1d196c06f6c0:3d38f4c1d21a4f888fe5ed13cf4da96c
[W 12:49:13.812 NotebookApp] Replacing stale connection: ed51175a-66ef-4154-8209-1d196c06f6c0:3d38f4c1d21a4f888fe5ed13cf4da96c
[I 12:49:30.119 NotebookApp] Interrupted...
[I 12:49:30.119 NotebookApp] Shutting down 2 kernels
[I 12:49:30.120 NotebookApp] Kernel shutdown: 55be3dfa-8973-4c59-8718-a5b9078a9bb3
[I 12:49:30.190 NotebookApp] Starting buffering for 55be3dfa-8973-4c59-8718-a5b9078a9bb3:b5e34d690325416b8210b32e759bd997
[I 12:49:30.244 NotebookApp] Kernel shutdown: 55be3dfa-8973-4c59-8718-a5b9078a9bb3
Traceback (most recent call last):
  File "/root/projects/binanceapp/venv/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/notebook/notebookapp.py", line 2361, in start
    self.cleanup_kernels()
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/notebook/notebookapp.py", line 2146, in cleanup_kernels
    run_sync(self.kernel_manager.shutdown_all())
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/jupyter_client/utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 301, in _async_shutdown_all
    futs = [ensure_async(self.shutdown_kernel(kid, now=now)) for kid in kids]
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 301, in <listcomp>
    futs = [ensure_async(self.shutdown_kernel(kid, now=now)) for kid in kids]
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 304, in shutdown_kernel
    self.pinned_superclass.shutdown_kernel(self, kernel_id, now=now, restart=restart)
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/jupyter_client/utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 253, in _async_shutdown_kernel
    self.remove_kernel(kernel_id)
  File "/root/projects/binanceapp/venv/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 291, in remove_kernel
    return self._kernels.pop(kernel_id)
KeyError: '55be3dfa-8973-4c59-8718-a5b9078a9bb3'
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[I 12:50:03.719 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 12:50:04.102 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 12:50:04.105 NotebookApp] Serving notebooks from local directory: /root/projects/binanceapp
[I 12:50:04.105 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 12:50:04.106 NotebookApp] http://localhost:8888/
[I 12:50:04.106 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 12:50:04.112 NotebookApp] No web browser found: could not locate runnable browser.
[W 12:50:11.940 NotebookApp] Notebook gmail_send_mail.ipynb is not trusted
[I 12:50:12.056 NotebookApp] Kernel started: c7c4e7da-61ec-47aa-bfc4-9e3c8a82a416, name: python3
ERROR:asyncio:Exception in callback <TaskStepMethWrapper object at 0x7f8a79e45780>()
handle: <Handle <TaskStepMethWrapper object at 0x7f8a79e45780>()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>
[I 12:52:12.518 NotebookApp] Saving file at /gmail_send_mail.ipynb
[I 13:28:12.546 NotebookApp] Saving file at /gmail_send_mail.ipynb
[I 13:34:12.566 NotebookApp] Saving file at /gmail_send_mail.ipynb
[I 13:36:12.501 NotebookApp] Saving file at /gmail_send_mail.ipynb
[I 14:10:12.155 NotebookApp] Saving file at /gmail_send_mail.ipynb
[I 14:52:02.643 NotebookApp] Starting buffering for c7c4e7da-61ec-47aa-bfc4-9e3c8a82a416:69e8f77b234f485a81cf3f6942722036
[I 16:16:13.494 NotebookApp] Kernel started: 63072d49-22bc-4182-b41c-beff9bb550f6, name: python3
[I 16:17:03.998 NotebookApp] Starting buffering for 63072d49-22bc-4182-b41c-beff9bb550f6:5c29f8acc59f4cb5b1f2a4ef4c79cef9
[I 16:17:15.761 NotebookApp] Kernel shutdown: 63072d49-22bc-4182-b41c-beff9bb550f6
[W 16:17:15.762 NotebookApp] delete /binance_trial/binance_first.ipynb
[W 16:17:15.770 NotebookApp] delete /binance_trial/nohup.out
[W 16:17:15.771 NotebookApp] delete /binance_trial/README.md
[W 16:17:15.773 NotebookApp] delete /binance_trial/requirements.txt
[W 16:41:34.960 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 16:41:35.557 NotebookApp] Kernel started: 00e51626-23a4-4066-a270-85d0c76b9f31, name: python3
[I 17:41:50.874 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 17:41:52.052 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 17:41:52.053 NotebookApp] The port 8888 is already in use, trying another port.
[I 17:41:52.053 NotebookApp] The port 8889 is already in use, trying another port.
[I 17:41:52.056 NotebookApp] Serving notebooks from local directory: /root/projects/binance_first
[I 17:41:52.057 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 17:41:52.057 NotebookApp] http://localhost:8890/
[I 17:41:52.057 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 17:41:52.064 NotebookApp] No web browser found: could not locate runnable browser.
[I 17:44:08.869 NotebookApp] Interrupted...
[I 17:44:08.870 NotebookApp] Shutting down 0 kernels
[I 17:44:08.870 NotebookApp] Shutting down 0 terminals
[I 18:03:46.952 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 18:03:47.318 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 18:03:47.318 NotebookApp] The port 8888 is already in use, trying another port.
[I 18:03:47.321 NotebookApp] Serving notebooks from local directory: /root/projects/binance_first
[I 18:03:47.321 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 18:03:47.322 NotebookApp] http://localhost:8889/
[I 18:03:47.322 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 18:03:47.327 NotebookApp] No web browser found: could not locate runnable browser.
[I 18:21:13.272 NotebookApp] Interrupted...
[I 18:21:13.273 NotebookApp] Shutting down 0 kernels
[I 18:21:13.273 NotebookApp] Shutting down 0 terminals
[I 18:21:35.400 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 18:21:35.759 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 18:21:35.763 NotebookApp] Serving notebooks from local directory: /root/projects/binance_first
[I 18:21:35.763 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 18:21:35.763 NotebookApp] http://localhost:8888/
[I 18:21:35.763 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 18:21:35.769 NotebookApp] No web browser found: could not locate runnable browser.
[W 18:21:42.616 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 18:21:43.024 NotebookApp] Kernel started: 032509df-480a-4f2a-b9ef-06330dfc2b69, name: python3
ERROR:asyncio:Exception in callback <TaskStepMethWrapper object at 0x7ffbf49463c8>()
handle: <Handle <TaskStepMethWrapper object at 0x7ffbf49463c8>()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>
[I 18:23:43.084 NotebookApp] Saving file at /binance_first.ipynb
[W 18:23:43.085 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 18:49:43.208 NotebookApp] Saving file at /binance_first.ipynb
[W 18:49:43.208 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 18:51:43.398 NotebookApp] Saving file at /binance_first.ipynb
[W 18:51:43.398 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 18:55:43.095 NotebookApp] Saving file at /binance_first.ipynb
[W 18:55:43.096 NotebookApp] Notebook binance_first.ipynb is not trusted
[I 18:57:43.060 NotebookApp] Saving file at /binance_first.ipynb
[W 18:57:43.061 NotebookApp] Notebook binance_first.ipynb is not trusted
